name: Scheduled Scraping and Sending to Discord

on:
  schedule:
    - cron: '0 11,17 * * *'  # Twice a day at 11 AM and 5 PM UTC
  push:
    branches:
      - main  # Replace with the name of your main branch

jobs:
  scrape_and_send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script to get data
        id: discord-message
        run: |
          # Run the script and capture the output
          SCRAPE_DATA=$(python scripts/scrape_data.py)

          # Print the output for debugging purposes
          echo "SCRAPE_DATA: $SCRAPE_DATA"

          # Enclose the data in triple backticks to indicate Markdown code block
          echo "SCRAPE_DATA: |
      \`\`\`
      $SCRAPE_DATA
      \`\`\`" >> "$GITHUB_OUTPUT"


      - name: Send to Discord
        run: python scripts/send_to_discord.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_MESSAGE: ${{ steps.discord-message.outputs.SCRAPE_DATA }}
