name: Scheduled Scraping and Sending to Discord

on:
  schedule:
    - cron: '0 14,20 * * 1-5'  # Twice a day at 2 PM and 8 PM UTC-3 from Monday to Friday
  push:
    branches:
      - main  # Replace with the name of your main branch

jobs:
  scrape_and_send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send to Discord
        run: python scripts/send_to_discord.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
